app/urls.py
from django.urls import path
from .views import IndexView, Test_bookView, Target_1900View

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('testbook/', Test_bookView.as_view(), name='test_book'),
    path('target1900/', Target_1900View.as_view(), name='target_1900')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models

class Test_book(models.Model):

    number = models.IntegerField(
        verbose_name='番号'
    )

    en_word = models.CharField(
        verbose_name='英単語',
        max_length=200,
    )

    jp_word = models.CharField(
        verbose_name='日本語訳',
        max_length=200,
    )

    def __str__(self):
        return self.en_word

    class Meta:
        verbose_name = 'テスト単語帳'
        verbose_name_plural = 'テスト単語帳'

class Target_1900(models.Model):
    number = models.IntegerField(
        verbose_name='番号'
    )

    en_word = models.CharField(
        verbose_name='英単語',
        max_length=200,
    )

    jp_word = models.CharField(
        verbose_name='日本語訳',
        max_length=200,
    )

    def __str__(self):
        return self.en_word

    class Meta:
        verbose_name = 'ターゲット1900'
        verbose_name_plural = 'ターゲット1900'

app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from .models import Test_book, Target_1900

class IndexView(TemplateView):
    template_name = 'index.html'

class Test_bookView(ListView):
    model = Test_book
    template_name = 'test_book.html'

class Target_1900View(ListView):
    model = Target_1900
    template_name = 'target_1900.html'

app/templates/Test_book.html
{% load static %}
<html>
<head>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">
    <style>

        body {
            padding: 50px;
        }

    </style>
</head>
<body>
    <h1>
        英単語テスト
    </h1>
    <div id="app" class="row">
        <!-- クイズを表示する部分 -->
        <div class="offset-3 col-6">
            <div class="card">
                <div class="card-body">
                    <p class="badge badge-dark">第 [|[ questionIndex+1 ]|] 問  ([|[ questionIndex+1 ]|]/8)</p>
                    <br>
                    <h4 class="card-title">[|[ currentQuestion.question ]|]</h4>
                    <hr>
                    <button type="button" 
                    class="btn btn-primary btn-lg btn-block text-left"
                    v-for="(answer, index) in currentQuestion.answers"
                    @click="addAnswer(index)">
                        [|[ index+1 ]|]. [|[ answer ]|]
                    </button>
                </div>
            </div>
        </div>
        <!-- 結果表示する部分 -->
        <div class="offset-3 col-6" v-if="completed">
            <div class="card">
                <div class="card-body">
                    <p class="badge badge-dark">結果</p>
                    <div v-for="(question,index) in this.questions">
                        <h4 class="card-title">[|[ question.question ]|]</h4>
                        <ul>
                            <li v-for="answer in question.answers">[|[ answer ]|]</li>
                        </ul>
                        <span v-if="question.answer == answers[index]">正解 &#x1F44D;（[|[ question.answers[question.answer] ]|]）</span>
                        <span v-else>不正解 &#x1F622;<br>正解は「[|[ question.answers[question.answer] ]|]」でした。</span>
                        <hr>
                    </div>
                    <p>[|[ correctCount ]|] 問正解しました！</p>
                </div>
            </div>
        </div>
    </div>
</body>
<script src="{% static "js/vue.js" %}"></script>
<script>
    var words_array = {
        {% for test_book in test_book_list %}
        {{ test_book.number }} : {
            en : "{{ test_book.en_word }}",
            jp : "{{ test_book.jp_word }}",
        },
        {% endfor %}
    };
    console.log(words_array);
</script>
<script src="{% static "js/quiz.js" %}"></script>
</html>

app/templates/index.html
<html>
<head>
</head>
<body>
    indextest
</body>
</html>

app/templates/target_1900.html
{% load static %}
<html>
<head>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {padding: 50px;}
    </style>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
</head>
<body>
    <h1 class="text-center">
        ターゲット1900
    </h1>
    <div id="app" class="row">
        <!-- クイズを表示する部分 -->
        <div class="offset-3 col-6">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">範囲を入力して問題数を選んでください</h4>
                        <input type="number" v-model="start_index">
                        <p>〜</p>
                        <input type="number" v-model="end_index">
                        <select v-model="selected">
                            <option disabled value="">Please select one</option>
                            <option v-for="option in options" v-bind:value="option.value">
                                [|[ option.text ]|]
                            </option>
                        </select>
                        <hr>
                        <button type="button" @click="make_question_array(); start(); disabled = true;">
                            決定
                        </button>
                </div>
            </div>
        </div>
        <!-- クイズを表示する部分 -->
        <div class="offset-3 col-6" v-if="init_or_not">
            <div class="card">
                <div class="card-body">
                    <p class="badge badge-dark">第 [|[ questionIndex+1 ]|] 問  ([|[ questionIndex+1 ]|]/[|[ questions.length ]|])</p>
                    <br>
                    <h4 class="card-title">[|[ currentQuestion.question ]|]</h4>
                    <hr>
                    <button type="button" 
                    class="btn btn-primary btn-lg btn-block text-left"
                    v-for="(answer, index) in currentQuestion.answers"
                    @click="addAnswer(index)">
                        [|[ index+1 ]|]. [|[ answer ]|]
                    </button>
                </div>
            </div>
        </div>
        <!-- 結果表示する部分 -->
        <div class="offset-3 col-6" v-if="completed && init_or_not">
            <div class="card">
                <div class="card-body">
                    <p class="badge badge-dark">結果</p>
                    <div>
                    <p>[|[ correctCount ]|] 問正解しました！</p>
                    <hr>
                    </div>
                    <div v-for="(question,index) in this.questions">
                        <h4 class="card-title">[|[ question.question ]|]</h4>
                        <ul>
                            <li v-for="answer in question.answers">[|[ answer ]|]</li>
                        </ul>
                        <span v-if="question.answer == answers[index]">正解 &#x1F44D;「[|[ question.answers[question.answer] ]|]」</span>
                        <span v-else>不正解 &#x1F622;<br>正解は「[|[ question.answers[question.answer] ]|]」でした。</span>
                        <hr>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
<script src="{% static "js/vue.js" %}"></script>
<script>
    var words_array = {
        {% for target_1900 in target_1900_list %}
        {{ target_1900.number }} : {
            en : "{{ target_1900.en_word }}",
            jp : "{{ target_1900.jp_word }}",
        },
        {% endfor %}
    };
    console.log(words_array);
</script>
<script src="{% static "js/quiz2.js" %}"></script>
</html>

app/templates/test_book.html
{% load static %}
<html>
<head>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {padding: 50px;}
    </style>
    <meta name="viewport" content="width=device-width">
</head>
<body>
    <h1>
        英単語テスト
    </h1>
    <div id="app" class="row">
        <!-- クイズを表示する部分 -->
        <div class="offset-3 col-6">
            <div class="card">
                <div class="card-body">
                    <p class="badge badge-dark">第 [|[ questionIndex+1 ]|] 問  ([|[ questionIndex+1 ]|]/8)</p>
                    <br>
                    <h4 class="card-title">[|[ currentQuestion.question ]|]</h4>
                    <hr>
                    <button type="button" 
                    class="btn btn-primary btn-lg btn-block text-left"
                    v-for="(answer, index) in currentQuestion.answers"
                    @click="addAnswer(index)">
                        [|[ index+1 ]|]. [|[ answer ]|]
                    </button>
                </div>
            </div>
        </div>
        <!-- 結果表示する部分 -->
        <div class="offset-3 col-6" v-if="completed && init_or_not">
            <div class="card">
                <div class="card-body">
                    <p class="badge badge-dark">結果</p>
                    <p>[|[ correctCount ]|] 問正解しました！</p>
                    <div v-for="(question,index) in this.questions">
                        <h4 class="card-title">[|[ question.question ]|]</h4>
                        <ul>
                            <li v-for="answer in question.answers">[|[ answer ]|]</li>
                        </ul>
                        <span v-if="question.answer == answers[index]">正解 &#x1F44D;（[|[ question.answers[question.answer] ]|]）</span>
                        <span v-else>不正解 &#x1F622;<br>正解は「[|[ question.answers[question.answer] ]|]」でした。</span>
                        <hr>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
<script src="{% static "js/vue.js" %}"></script>
<script>
    var words_array = {
        {% for test_book in test_book_list %}
        {{ test_book.number }} : {
            en : "{{ test_book.en_word }}",
            jp : "{{ test_book.jp_word }}",
        },
        {% endfor %}
    };
    console.log(words_array);
</script>
<script src="{% static "js/quiz.js" %}"></script>
</html>